<<<<<<< HEAD
server:

  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:ms_catalogo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
=======
server:
  port: 8081


spring:
  application:
    name: ms-catalogo-service

  datasource:
    url: jdbc:mysql://localhost:3306/ms_catalogo
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
>>>>>>> bdeef91e8e6bc728435a7eee12b8f683c37c6c0a
