<<<<<<< HEAD
spring:
  application:
    name: ms-catalogo-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070
=======

spring:
  application:
    name: ms-catalogo-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070



>>>>>>> bdeef91e8e6bc728435a7eee12b8f683c37c6c0a
